plugins {
    id 'com.android.library'
}

android {
    compileSdk = libs.versions.compileSdkVersion.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.minSdkVersion.get().toInteger()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            // Let the app module take care of this
            minifyEnabled false
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlin {
        jvmToolchain(21)
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig true
    }

    flavorDimensions 'gms'
    productFlavors {
        nongms {
            dimension 'gms'
        }
        fullgms {
            dimension 'gms'
        }
    }
    namespace 'com.thewizrd.extras'
    lint {
        targetSdk libs.versions.targetSdkVersion.get().toInteger()
    }
    testOptions {
        targetSdk libs.versions.targetSdkVersion.get().toInteger()
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    implementation project(":shared_resources")
    implementation project(":weathericons")

    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.core.ktx
    implementation libs.constraintlayout
    implementation libs.recyclerview
    implementation libs.work.runtime.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.material
}